# Generated by Django 6.0.2 on 2026-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketestado_descripcion_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketestado',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
